name: Broken Certificates Notifications

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cert check
        env:
          HOOK_URL: ${{ secrets.HOOK_URL }}
          TARGET_DOMAIN: ${{ secrets.TARGET_DOMAIN }}
        run: bash cert_check.sh
