name: Broken Link Notifications

on:
  schedule:
    - cron: '0 9-18 * * 1-5'
  workflow_dispatch:

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: link check
        run: bash main.sh
        working-directory: ./link_check
